query Home($paginate: PaginationInput!) {
  myMessages(paginate: $paginate) {
    items {
      uuid
      correspondent {
        uuid
        encSecretDisplayName
      }
      encryptedData {
        encSenderName
        encSubject
        encReplyingToMessageId
        encCategory
        encContent
        encNotificationData {
          encUrgency
          encShowUrlOnClick
        }
      }
    }
    hasMore
    prevCursor
    nextCursor
  }
}
