version: '3'

services:
  postgres:
    image: postgres:14-alpine
    container_name: nota-db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: superweakpassword
      POSTGRES_USER: nota
      POSTGRES_DB: nota
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
