mutation Login($input: UserLoginDTO!) {
  login(input: $input) {
    viewer {
      uuid
      symKeyEncPrivateKeyJWK
      symKeyEncPrivateKeyIV
      publicKeyJWK
      encPublicName
      encPublicNameIV
    }
    accessToken
  }
}
